# Generated by Django 4.1.5 on 2023-01-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(upload_to='blogs/images'),
        ),
    ]
