# Generated by Django 4.1.5 on 2023-01-08 07:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
